### ISSUE TITLE
Move data to a server or other remote hosting?

### ISSUE THREAD

**Issue by MoralCode** [petegordon/VaccinateOhio_KrogerScraper#1]
I notice that data in this repo is just being committed to https://github.com/petegordon/VaccinateOhio_KrogerScraper/tree/main/ZipLocationsVaccines every minute or so and the repo as a whole has at least 4000 commits.

I think there might be a better way to host data and i'd love to discuss how your app uses this data (i dont see any JSON data through the network tab in inspect element).

If you're interested, I'd love to work with you to help set up something that would make it easier for more people to potentially use (thinking something similar to how vaccinespotter.org posts JSON files)

**Comment by petegordon** [comment]
Hi sorry for the delay. All of the data is aggregated in one “availability” file for Kroger and Ohio; it refreshes every 10 minutes and it also has a changing name (unixtime stamp only changes). Could use that one file... but right now you’d have to loop through the directory looking for the partial name. I could add a static output name in addition to that if you’d like? Also, checkout the RiteAid repo (same approach) https://github.com/petegordon/VaccinateOhio_KrogerScraper/blob/main/kroger_availability_1617108141680.json
